sudo: required

os:
  - windows
  - linux
  - osx

language: python

env:
  - PYV=3.4
  - PYV=3.5
  - PYV=3.6
  - PYV=3.7
#  - PYV=3.3 # Apt fails in this docker image
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
