sudo: required

matrix:
  include:
    - os: linux
      language: python
      python: 3.4
      before_install:
        - pip install --upgrade --force-reinstall pandas
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.7
    - os: osx
      language: generic
      addons:
        homebrew:
          # update: true
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
    - os: windows
      language: bash
      before_install:
        - cinst -y python3
# command to run tests
script:
  - python3 setup.py test
